In [2]:
import numpy as np
marks = np.array([70,80,99,76, 98])

# Student marks
print("Marks", marks)
print("Average", np.mean(marks))
print("Lowest", np.min(marks))
print("Highest", np.max(marks))

Marks [70 80 99 76 98]
Average 84.6
Lowest 70
Highest 99


In [3]:
# Sales data
sales = np.array([1000, 1500, 1200, 1800, 2000])

print(sales)
print("Total", np.sum(sales))
print("Average", np.mean(sales))

[1000 1500 1200 1800 2000]
Total 7500
Average 1500.0


In [6]:
# Temperature analysis
temperatures = np.array([33, 24, 55, 42, 41, -3, -9 ])

print(temperatures)
print("Average", np.mean(temperatures))
print("Maximum", np.max(temperatures))
print("Minimum", np.min(temperatures))

[33 24 55 42 41 -3 -9]
Average 26.142857142857142
Maximum 55
Minimum -9


In [24]:
# 2D array

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)
print(data.shape)

data[1:, 2]

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


array([60, 90])

In [26]:
image = np.array([
    [0,   0,   255],
    [0,   255, 0],
    [255, 0,   0]
])

print(image)



[[  0   0 255]
 [  0 255   0]
 [255   0   0]]


In [28]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 + v2)

np.dot(v1, v2)

[5 7 9]


32

In [37]:
import numpy as np

marks = np.array([65, 80, 75, 90, 55, 88, 92])

# 1. Find average
print("Average Marks: ", np.mean(marks))
# 2. Find highest mark
print("highest Marks:", np.max(marks))
# 3. Find lowest mark
print("lowest Marks:", np.min(marks))
# 4. Find marks greater than 80
print("marks greater than 80:", marks > 80)
# 5. Sort the marks
print("Sort:", np.sort(marks))
# 6. Count how many students scored above 80
count = np.sum(marks > 80)
print(count)

Average Marks:  77.85714285714286
highest Marks: 92
lowest Marks: 55
marks greater than 80: [False False False  True False  True  True]
Sort: [55 65 75 80 88 90 92]
3
